/*
 * Copyright 2010-2018 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license
 * that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.checkers;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.JUnit3RunnerWithInners;
import org.jetbrains.kotlin.test.KotlinTestUtils;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.generators.tests.TestsPackage}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/diagnostics/testsSpec")
@TestDataPath("$PROJECT_ROOT")
@RunWith(JUnit3RunnerWithInners.class)
public class DiagnosticsTestSpecGenerated extends AbstractDiagnosticsTestSpec {
    private void runTest(String testDataFilePath) throws Exception {
        KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
    }

    public void testAllFilesPresentInTestsSpec() throws Exception {
        KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/diagnostics/testsSpec"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
    }

    @TestMetadata("compiler/testData/diagnostics/testsSpec/s16.30_WhenExpression")
    @TestDataPath("$PROJECT_ROOT")
    @RunWith(JUnit3RunnerWithInners.class)
    public static class S16_30_WhenExpression extends AbstractDiagnosticsTestSpec {
        private void runTest(String testDataFilePath) throws Exception {
            KotlinTestUtils.runTest(this::doTest, TargetBackend.ANY, testDataFilePath);
        }

        public void testAllFilesPresentInS16_30_WhenExpression() throws Exception {
            KotlinTestUtils.assertAllTestsPresentByMetadata(this.getClass(), new File("compiler/testData/diagnostics/testsSpec/s16.30_WhenExpression"), Pattern.compile("^(.+)\\.kt$"), TargetBackend.ANY, true);
        }

        @TestMetadata("p1s1_pos.kt")
        public void testP1s1_pos() throws Exception {
            runTest("compiler/testData/diagnostics/testsSpec/s16.30_WhenExpression/p1s1_pos.kt");
        }

        @TestMetadata("p1s1_pos.kt")
        public void testP1s2_pos() throws Exception {
            runTest("compiler/testData/diagnostics/testsSpec/s16.30_WhenExpression/p1s1_pos.kt");
        }

        @TestMetadata("p1s1_pos.kt")
        public void testP1s3_pos() throws Exception {
            runTest("compiler/testData/diagnostics/testsSpec/s16.30_WhenExpression/p1s1_pos.kt");
        }

        @TestMetadata("p1s1_pos.kt")
        public void testP1s4_pos() throws Exception {
            runTest("compiler/testData/diagnostics/testsSpec/s16.30_WhenExpression/p1s1_pos.kt");
        }

        @TestMetadata("p1s1_pos.kt")
        public void testP1s5_neg() throws Exception {
            runTest("compiler/testData/diagnostics/testsSpec/s16.30_WhenExpression/p1s1_pos.kt");
        }
    }
}
